name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Replace <USERNAME> and <SPACE_NAME> with your actual HF info
          git push --force https://nveshaan:$HF_TOKEN@huggingface.co/spaces/nveshaan/f1_olap main
